from tkinter import *
root=Tk()
root.title("Book Bank System Online")
root.geometry('600x600')
root.minsize(400,400)
root.maxsize(1440,900)
root.configure(bg='#ebedef')
headingFrame1 = Frame(root,bg="#FFBB00",bd=5)
headingFrame1.place(relx=0.2,rely=0.1,relwidth=0.6,relheight=0.16)
headingLabel = Label(headingFrame1, text="Book Bank System", bg='black', fg='white', font=('Courier',15))
headingLabel.place(relx=0,rely=0, relwidth=1, relheight=1)
btn1 = Button(root,text="Login/Register",bg='black', fg='white')
btn1.place(relx=0.28,rely=0.4, relwidth=0.45,relheight=0.1)
btn2 = Button(root,text="Select Book",bg='black', fg='white')
btn2.place(relx=0.28,rely=0.5, relwidth=0.45,relheight=0.1)
btn3 = Button(root,text="Return Book",bg='black', fg='white')
btn3.place(relx=0.28,rely=0.6, relwidth=0.45,relheight=0.1)
btn4 = Button(root,text="Exit",bg='black', fg='white',command=root.destroy)
btn4.place(relx=0.28,rely=0.7, relwidth=0.45,relheight=0.1)
root.mainloop()
