from tkinter import *
class ticket:
    def Home(self):
        root0=Tk()
        root0.geometry('925x500+200+100')
        root0.resizable(False,False)
        root0.config(bg='#fff')
        heading=Label(root0,text="E -Ticket Reservation System",font=("Arial",30,"bold"),fg='blue',bg='#fff')
        heading.place(x=235,y=50)
        Button(root0,text="Login",width=15,font=("Arial",20),fg='black',bg='white').place(x=345,y=130)
        Button(root0,text="Register",width=15,font=("Arial",20),fg='black',bg='white').place(x=345,y=190)
        Button(root0,text="Book Ticket",width=15,font=("Arial",20),fg='black',bg='white').place(x=345,y=250)
        Button(root0,text="Cancel Ticket",width=15,font=("Arial",20),fg='black',bg='white').place(x=345,y=310)
        Button(root0,text="Exit",width=15,font=("Arial",20),fg='black',bg='white',command=root0.destroy).place(x=345,y=370)
        root0.mainloop()

    def login(self):
        root1=Tk()
        root1.geometry('925x500+200+100')
        root1.config(bg="#fff")
        heading=Label(root1,text="Login",font=("Arial",30,"bold"),fg='blue',bg='#fff')
        heading.place(x=435,y=50)
        user_name=Label(root1,text="User Name",font=("Arial",25),fg='blue',bg='#fff')
        user_name.place(x=150,y=160)
        passwd=Label(root1,text="Password",font=("Arial",25),fg='blue',bg='#fff')
        passwd.place(x=150,y=260)
        usr=Entry(root1,width=25,bg='#fff',fg='blue',font=("Arial",25))
        usr.place(x=350,y=160)
        paas=Entry(root1,width=25,bg='#fff',fg='blue',font=("Arial",25))
        paas.place(x=350,y=260)
        Button(root1,text="Login",width=15,border=0,highlightthickness=0,font=("Arial",20),fg='black',bg='white',command=root1.destroy).place(x=365,y=370)
        root1.mainloop()

o=ticket()
o.login()